# Generated by Django 4.0 on 2021-12-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='dt_criacao')),
                ('modificado_em', models.DateTimeField(auto_now_add=True, db_column='dt_modificado')),
                ('ativo', models.BooleanField(db_column='cs_active', default=True, null=True)),
                ('nome', models.CharField(db_column='tx_nome', max_length=200)),
                ('email', models.CharField(db_column='tx_email', max_length=200)),
                ('dt_nascimento', models.DateTimeField(db_column='dt_nascimento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
