# Generated by Django 4.0 on 2021-12-27 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_column='dt_criacao')),
                ('modificado_em', models.DateTimeField(auto_now_add=True, db_column='dt_modificado')),
                ('ativo', models.BooleanField(db_column='cs_active', default=True)),
                ('nome_receita', models.CharField(db_column='tx_nome_receita', max_length=200)),
                ('ingredientes', models.TextField(db_column='tx_ingredientes')),
                ('modo_preparo', models.TextField(db_column='tx_modo_preparo')),
                ('tempo_preparo', models.IntegerField(db_column='nb_tempo_preparo')),
                ('rendimento', models.CharField(db_column='tx_rendimento', max_length=100)),
                ('categoria', models.CharField(db_column='tx_categoria', max_length=100)),
                ('pessoa', models.ForeignKey(db_column='id_pessoa', on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoa')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
