# Generated by Django 4.0 on 2021-12-29 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('receitas', '0002_receita_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='pessoa',
            field=models.ForeignKey(db_column='id_pessoa', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
